# Generated by Django 6.0.7 on 2026-07-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='copyright_text',
            field=models.CharField(default='© 2026 Vetri Technology Solutions | Developed and Maintained by Vetri IT Systems Pvt.', max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/vetriitsurandai?igsh=MW5mYmhsZnU5N3Y3dQ%3D%3D', max_length=300),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='vis_url',
            field=models.URLField(default='https://www.vetriit.com/', max_length=300),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='vts_url',
            field=models.URLField(default='https://www.vetritechnologysolutions.in/', max_length=300),
        ),
    ]
