# Generated by Django 6.0.7 on 2026-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_footeraddress_contactinfo_copyright_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='About Vetri Training – Online IT Courses with Placement Support', max_length=255)),
                ('hero_subtitle', models.TextField(default='Empowering the next generation of IT Professionals with foundational knowledge and industry-ready skills')),
                ('story_heading', models.CharField(default='Our Story – Building Job-Oriented Training Programs', max_length=255)),
                ('story_paragraph1', models.TextField(default='VTS was founded with a simple observation — many learners struggle to enter the IT industry not due to lack of talent, but because they lack practical exposure, confidence, and guided direction.')),
                ('story_paragraph2', models.TextField(default='We built Vetri Technology Solutions to bridge this gap through structured training, real-time collaboration, and a strong learning ecosystem.')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='site/about/')),
                ('mascot_image', models.ImageField(blank=True, null=True, upload_to='site/about/')),
                ('cta_title', models.CharField(default='Ready to Start Your Career', max_length=255)),
                ('cta_body', models.TextField(default='Direct placement support and interview opportunities at our integrated IT startup ecosystem. Start your career with confidence!')),
                ('cta_avatar', models.ImageField(blank=True, null=True, upload_to='site/about/')),
            ],
            options={
                'verbose_name': 'About Intro (Hero/Story/Mascot/CTA)',
                'verbose_name_plural': 'About Intro (Hero/Story/Mascot/CTA)',
            },
        ),
        migrations.CreateModel(
            name='EcosystemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='site/about/ecosystem/')),
                ('title', models.CharField(max_length=150)),
                ('items_text', models.TextField(help_text='One item per line. Each line becomes one bullet point in the app.')),
                ('site_url', models.URLField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='site/about/enroll/')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.FloatField()),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('decimals', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='site/about/journey/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionVisionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='site/about/mission_vision/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('items_text', models.TextField(help_text='One item per line. Each line becomes one bullet point in the app.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApproachCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
