# Generated by Django 6.0.7 on 2026-07-14 06:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_aboutintro_ecosystemcard_enrollitem_impactstat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='IT Training, Internship & Career Support', max_length=255)),
                ('hero_description', models.TextField(default='This platform is designed for learners who want to build practical IT skills through structured training programs. Along with training, learners are informed about available IT services and consultancy support.')),
                ('hero_bg_image', models.ImageField(blank=True, null=True, upload_to='site/home/')),
                ('whoweare_image', models.ImageField(blank=True, null=True, upload_to='site/home/')),
                ('established_title', models.CharField(default='Established in 2021', max_length=150)),
                ('established_text', models.TextField(default='Specializing in IT training, placement, and custom software development in Surandai.')),
                ('whoweare_heading', models.CharField(default='Why Choose Our Training Programs', max_length=255)),
                ('whoweare_description', models.TextField(default='We are a training centre that helps students learn IT skills. We also have our own IT startup where real software work is done. Along with training, we provide consultation services to guide students in career and job-related matters.')),
                ('whychoose_mascot_image', models.ImageField(blank=True, null=True, upload_to='site/home/')),
                ('howitworks_heading', models.CharField(default='How Our Training Works', max_length=255)),
                ('howitworks_subtext', models.TextField(default='Follow our proven 4-step journey to transform from a beginner into an industry-ready tech professional.')),
                ('projects_heading', models.CharField(default='Student Projects & Success Stories', max_length=255)),
                ('projects_subtext', models.CharField(default='See what our students have built and achieved', max_length=255)),
                ('stories_heading', models.CharField(default='Students success stories', max_length=255)),
                ('stories_subtext', models.CharField(default='watch our latest students success stories..', max_length=255)),
                ('cta_heading', models.CharField(default='Start your Learning Journey today!', max_length=255)),
                ('cta_subtext', models.TextField(default='Get expert guidance, structured training, and real-world skills that prepare you for career success.')),
                ('cta_mascot_image', models.ImageField(blank=True, null=True, upload_to='site/home/')),
            ],
            options={
                'verbose_name': 'Home Intro (Hero/WhoWeAre/Headings/CTA)',
                'verbose_name_plural': 'Home Intro (Hero/WhoWeAre/Headings/CTA)',
            },
        ),
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site/home/projects/')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('tag', models.CharField(max_length=100)),
                ('tall', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='site/home/steps/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site/home/stories/')),
                ('video', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='site/home/stories/')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
