# Generated by Django 6.0.7 on 2026-07-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='courses/covers/')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('highlight', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('overview', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Data', 'Data'), ('Design', 'Design'), ('Development', 'Development'), ('Emerging Tech', 'Emerging Tech')], max_length=20)),
                ('brochure_file', models.FileField(blank=True, null=True, upload_to='courses/brochures/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BenefitSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('items_text', models.TextField(help_text='One item per line. Each line becomes one bullet point in the app.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='courses/tool_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
